//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontV3.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductsID { get; set; }
        public string ProdName { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public int ProdStatusID { get; set; }
        public int UnitsSold { get; set; }
        public decimal Price { get; set; }
        public int ShippingID { get; set; }
        public int DeptID { get; set; }
        public int EmployeeID { get; set; }
        public string ProdImage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ProductStatus ProductStatus { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
